[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/setup/healthz"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[[deploy.volumes]]
name = "data"
mountTo = "/data"

[variables]
PORT = "8080"
